export const ADD_LAYER     = 'ADD_LAYER';
export const TOGGLE_LAYER  = 'TOGGLE_LAYER';
export const UPDATE_INFO   = 'UPDATE_INFO';

export const FETCH_RESOURCES_BEGIN    = 'FETCH_RESOURCES_BEGIN';
export const FETCH_RESOURCES_SUCCESS  = 'FETCH_RESOURCES_SUCCESS';
export const FETCH_RESOURCES_FAILURE  = 'FETCH_RESOURCES_FAILURE';