import type { StyleSpecification } from "maplibre-gl";

export const modernLand: StyleSpecification = {
  version: 8,
  name: "Modern Land",
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://api.maptiler.com/tiles/v3-openmaptiles/tiles.json?key=uXfXuebPlkoPXiY3TPcv",
    },
  },
  layers: [
    {
      id: "modern-background",
      type: "background",
      maxzoom: 0,
      layout: {
        visibility: "none",
      },
      paint: {
        "background-color": "rgb(123 162 141)",
        "background-opacity": 0.7,
      },
    },
    {
      id: "landuse-residential",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["==", ["get", "class"], "residential"],
      ],
      layout: { visibility: "none" },
      paint: { "fill-color": "hsl(47,13%,86%)", "fill-opacity": 1 },
    },
    {
      id: "landcover_grass",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      layout: { visibility: "none" },
      filter: ["==", ["get", "class"], "grass"],
      paint: { "fill-color": "hsl(82,46%,72%)", "fill-opacity": 0.45 },
    },
    {
      id: "landcover_wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "class"], "wood"],
      layout: { visibility: "none" },
      paint: {
        "fill-color": "hsl(82,46%,72%)",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 8, 0.6, 22, 1],
      },
    },
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      layout: { visibility: "none" },
      paint: { "fill-color": "rgba(192, 216, 151, 0.53)", "fill-opacity": 1 },
    },
    {
      id: "landcover-ice-shelf",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "subclass"], "ice_shelf"],
      layout: { visibility: "none" },
      paint: { "fill-color": "hsl(47,26%,88%)", "fill-opacity": 0.8 },
    },
    {
      id: "landcover-glacier",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "subclass"], "glacier"],
      layout: { visibility: "none" },
      paint: {
        "fill-color": "hsl(47,22%,94%)",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 0, 1, 8, 0.5],
      },
    },
    {
      id: "landcover_sand",
      type: "fill",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["match", ["get", "class"], ["sand"], true, false],
      layout: { visibility: "none" },
      paint: {
        "fill-antialias": false,
        "fill-color": "rgba(232, 214, 38, 1)",
        "fill-opacity": 0.3,
      },
    },
    {
      id: "landuse",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["==", ["get", "class"], "agriculture"],
      layout: { visibility: "none" },
      paint: { "fill-color": "#eae0d0" },
    },
    {
      id: "landuse_overlay_national_park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      layout: { visibility: "none" },
      filter: ["==", ["get", "class"], "national_park"],
      paint: {
        "fill-color": "#E1EBB0",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 5, 0, 9, 0.75],
      },
    },
    {
      id: "park_outline",
      type: "line",
      source: "openmaptiles",
      "source-layer": "park",
      layout: { visibility: "none" },
      paint: {
        "line-color": "rgba(159, 183, 118, 0.69)",
        "line-dasharray": [0.5, 1],
      },
    },
    {
      id: "building",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      layout: { visibility: "none" },
      paint: {
        "fill-color": "hsl(39,41%,86%)",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0.6, 14, 1],
        "fill-outline-color": "hsl(36,45%,80%)",
      },
    },
    {
      id: "admin_sub",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["match", ["get", "admin_level"], [4, 6, 8], true, false],
      layout: { visibility: "none" },
      paint: { "line-color": "hsl(0,0%,76%)", "line-dasharray": [2, 1] },
    },
    {
      id: "admin_country_z0-4",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      maxzoom: 5,
      filter: [
        "all",
        ["<=", ["get", "admin_level"], 2],
        ["==", ["geometry-type"], "LineString"],
        ["!", ["has", "claimed_by"]],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "hsla(0,8%,22%,0.51)",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          3,
          0.5,
          22,
          15,
        ],
      },
    },
    {
      id: "admin_country_z5-",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      minzoom: 5,
      filter: [
        "all",
        ["<=", ["get", "admin_level"], 2],
        ["==", ["geometry-type"], "LineString"],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "hsla(0,8%,22%,0.51)",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          3,
          0.5,
          22,
          15,
        ],
      },
    },
  ],
};
