import type { StyleSpecification } from "maplibre-gl";

export const modernRoads: StyleSpecification = {
  version: 8,
  name: "Modern Roads",
  center: [8.54806714892635, 47.37180823552663],
  zoom: 12.241790506353492,
  bearing: 0,
  pitch: 0,
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://api.maptiler.com/tiles/v3-openmaptiles/tiles.json?key=uXfXuebPlkoPXiY3TPcv",
    },
  },
  layers: [
    {
      id: "waterway-tunnel",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      layout: { visibility: "none" },
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "tunnel"],
      ],
      paint: {
        "line-color": "hsl(205,56%,73%)",
        "line-dasharray": [3, 3],
        "line-gap-width": ["interpolate", ["linear"], ["zoom"], 12, 0, 20, 6],
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          8,
          1,
          20,
          2,
        ],
      },
    },
    {
      id: "tunnel_railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 0,
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "tunnel"],
        ["==", ["get", "class"], "transit"],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-dasharray": [3, 3],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "road_area_pier",
      type: "fill",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["==", ["get", "class"], "pier"],
      ],
      layout: { visibility: "none" },
      paint: { "fill-antialias": true, "fill-color": "hsl(47,26%,88%)" },
    },
    {
      id: "road_pier",
      type: "line",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["pier"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(47,26%,88%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          15,
          1,
          17,
          4,
        ],
      },
    },
    // {
    //   id: "road_bridge_area",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "Polygon"],
    //     ["match", ["get", "brunnel"], ["bridge"], true, false],
    //   ],
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "hsl(47,26%,88%)", "fill-opacity": 0.5 },
    // },
    {
      id: "road_path",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["path", "track"], true, false],
      ],
      layout: {
        "line-cap": "square",
        "line-join": "bevel",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(0,0%,97%)",
        "line-dasharray": [1, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          10,
        ],
      },
    },
    {
      id: "road_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["minor", "service"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(215.3,25%,26.7%)",
        "line-width": [
          "interpolate",
          ["exponential", 2.25],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "tunnel_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          ["==", ["get", "class"], "minor_road"],
        ],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "#efefef",
        "line-dasharray": [0.36, 0.18],
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "tunnel_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            ["primary", "secondary", "tertiary", "trunk"],
            true,
            false,
          ],
        ],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(217.2,32.6%,17.5%)",
        "line-dasharray": [0.28, 0.14],
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          30,
        ],
      },
    },
    {
      id: "road_trunk_primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["primary", "trunk"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(217.2,32.6%,17.5%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          6,
          0.5,
          20,
          30,
        ],
      },
    },
    {
      id: "road_secondary_tertiary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["secondary", "tertiary"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(217.2,32.6%,17.5%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          20,
        ],
      },
    },
    {
      id: "road_major_motorway", // interstates
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "class"], "motorway"],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(217.2,32.6%,17.5%)",
        "line-offset": 0,
        "line-width": [
          "interpolate",
          ["exponential", 2.2],
          ["zoom"],
          8,
          1,
          16,
          10,
        ],
      },
    },
    {
      id: "railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["get", "class"], "transit"],
        ["!=", ["get", "brunnel"], "tunnel"],
      ],
      layout: { visibility: "none" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "railway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", ["get", "class"], "rail"],
      layout: { visibility: "none" },
      paint: {
        "line-color": "hsl(220,13%,91%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "road_major_rail_hatching",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      paint: {
        "line-color": "hsl(220,13%,91%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          10,
        ],
        "line-dasharray": [0.2, 8],
      },
      metadata: {},
      filter: [
        "all",
        ["!in", "brunnel", "bridge", "tunnel"],
        ["==", "class", "rail"],
      ],
    },
    {
      id: "waterway-bridge-case",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "bridge"],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "#bbbbbb",
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0.5,
          20,
          10,
        ],
      },
    },
    {
      id: "waterway-bridge",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "bridge"],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(205,56%,73%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "bridge_minor case",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "minor_road"],
        ],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "#dedede",
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0.5,
          20,
          10,
        ],
      },
    },
    {
      id: "bridge_major case",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          [
            "match",
            ["get", "class"],
            ["primary", "secondary", "tertiary", "trunk"],
            true,
            false,
          ],
        ],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "none",
      },
      paint: {
        "line-color": "#dedede",
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0.5,
          20,
          10,
        ],
      },
    },
    {
      id: "bridge_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "minor_road"],
        ],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "#efefef",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "bridge_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          [
            "match",
            ["get", "class"],
            ["primary", "secondary", "tertiary", "trunk"],
            true,
            false,
          ],
        ],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "none",
      },
      paint: {
        "line-color": "hsl(217.2,32.6%,17.5%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          30,
        ],
      },
    },
  ],
};
