import type { StyleSpecification } from "maplibre-gl";

export const modernLabels: StyleSpecification = {
  version: 8,
  name: "Labels",
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json",
    },
  },
  glyphs: "https://tiles.basemaps.cartocdn.com/fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "housenumber",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "housenumber",
      minzoom: 17,
      filter: ["==", ["geometry-type"], "Point"],
      layout: {
        "text-field": ["to-string", ["get", "housenumber"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        visibility: "none",
      },
      paint: {
        "text-color": "hsla(0,14%,57%,0.51)",
        "text-halo-color": "hsl(39,41%,86%)",
        "text-halo-width": 0.5,
      },
    },
    {
      id: "poi_label",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "poi",
      minzoom: 14,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        ["==", ["get", "rank"], 1],
      ],
      layout: {
        "icon-size": 1,
        "text-anchor": "top",
        "text-field": [
          "format",
          ["get", "name:latin"],
          "\n",
          {},
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-offset": [0, 0.5],
        "text-size": 11,
        visibility: "none",
      },
      paint: {
        "text-color": "#666",
        "text-halo-blur": 1,
        "text-halo-color": "rgba(255,255,255,0.75)",
        "text-halo-width": 1,
      },
    },
    {
      id: "airport-label",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "aerodrome_label",
      minzoom: 10,
      filter: ["all", ["has", "iata"]],
      layout: {
        "icon-size": 1,
        "text-anchor": "top",
        "text-field": [
          "format",
          ["get", "name:latin"],
          "\n",
          {},
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-offset": [0, 0.5],
        "text-size": 11,
        visibility: "none",
      },
      paint: {
        "text-color": "hsl(0,10%,25%)",
        "text-halo-blur": 0,
        "text-halo-color": "hsl(0,0%,100%)",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "road_major_label",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      filter: ["==", ["geometry-type"], "LineString"],
      layout: {
        visibility: "none",
        "symbol-placement": "line",
        "text-field": [
          "concat",
          ["get", "name:latin"],
          " ",
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-letter-spacing": 0.1,
        "text-rotation-alignment": "map",
        "text-size": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          10,
          8,
          20,
          14,
        ],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#000",
        "text-halo-color": "hsl(0,0%,100%)",
        "text-halo-width": 2,
      },
    },
    {
      id: "mountain_peak",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "mountain_peak",
      minzoom: 7,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        ["==", ["get", "rank"], 1],
      ],
      layout: {
        "icon-size": 1,
        "text-anchor": "bottom",
        "text-field": [
          "format",
          ["get", "name:latin"],
          " ",
          ["get", "name:nonlatin"],
          "\n",
          ["get", "ele"],
          " m\n▲",
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-offset": [0, 0.5],
        "text-size": 11,
        visibility: "none",
      },
      paint: {
        "text-color": "rgba(51, 51, 51, 1)",
        "text-halo-blur": 1,
        "text-halo-color": "rgba(255,255,255,1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "park-label",
      type: "symbol",
      metadata: { "mapbox:group": "1444849242106.713" },
      source: "openmaptiles",
      "source-layer": "park",
      minzoom: 0,
      filter: [
        "all",
        ["==", ["get", "rank"], 1],
        ["==", ["geometry-type"], "Point"],
      ],
      layout: {
        "text-allow-overlap": false,
        "text-field": [
          "format",
          ["get", "name:latin"],
          "\n",
          {},
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-ignore-placement": false,
        "text-letter-spacing": 0.1,
        "text-max-width": 9,
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          12,
          10,
          15,
          14,
        ],
        "text-transform": "none",
        visibility: "none",
      },
      paint: {
        "text-color": "rgba(38, 92, 46, 1)",
        "text-halo-color": "rgba(255,255,255,0.8)",
        "text-halo-width": 1.2,
      },
    },
    {
      id: "place_label_other",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 8,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        [
          "match",
          ["get", "class"],
          ["city", "continent", "country", "state"],
          false,
          true,
        ],
      ],
      layout: {
        "text-anchor": "center",
        "text-field": [
          "format",
          ["get", "name:latin"],
          "\n",
          {},
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 6,
        "text-size": ["interpolate", ["linear"], ["zoom"], 6, 10, 12, 14],
        visibility: "none",
      },
      paint: {
        "text-color": "hsl(0,10%,25%)",
        "text-halo-blur": 0,
        "text-halo-color": "hsl(0,0%,100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_label_city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 16,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        ["==", ["get", "class"], "city"],
      ],
      layout: {
        "text-field": [
          "format",
          ["get", "name:latin"],
          "\n",
          {},
          ["get", "name:nonlatin"],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 10,
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 12, 8, 16],
        visibility: "none",
      },
      paint: {
        "text-color": "hsl(0,0%,0%)",
        "text-halo-blur": 0,
        "text-halo-color": "hsla(0,0%,100%,0.75)",
        "text-halo-width": 2,
      },
    },
    {
      id: "country_label-other",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        ["==", ["get", "class"], "country"],
        ["!", ["has", "iso_a2"]],
      ],
      layout: {
        "text-field": ["to-string", ["get", "name:latin"]],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 10,
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 12, 8, 22],
        visibility: "none",
      },
      paint: {
        "text-color": "hsl(0,0%,13%)",
        "text-halo-blur": 0,
        "text-halo-color": "rgba(255,255,255,0.75)",
        "text-halo-width": 2,
      },
    },
    {
      id: "country_label",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 12,
      filter: [
        "all",
        ["==", ["geometry-type"], "Point"],
        ["==", ["get", "class"], "country"],
        ["has", "iso_a2"],
      ],
      layout: {
        "text-field": ["to-string", ["get", "name:latin"]],
        "text-font": ["Noto Sans Bold"],
        "text-max-width": 10,
        "text-size": ["interpolate", ["linear"], ["zoom"], 3, 12, 8, 22],
        visibility: "none",
      },
      paint: {
        "text-color": "hsl(0,0%,13%)",
        "text-halo-blur": 0,
        "text-halo-color": "rgba(255,255,255,0.75)",
        "text-halo-width": 2,
      },
    },
  ],
};
